# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "applejack")
Ingredient.create(name: "light rum")
Ingredient.create(name: "gin")
Ingredient.create(name: "dark rhum")
Ingredient.create(name: "sweet vermouth")
Ingredient.create(name: "strawberry schnapps")
Ingredient.create(name: "scotch")
Ingredient.create(name: "apricot brandy")
Ingredient.create(name: "triple sec")
Ingredient.create(name: "southern comfort")
Ingredient.create(name: "orange bitters")
Ingredient.create(name: "brandy")
Ingredient.create(name: "lemon vodka")
Ingredient.create(name: "blended whiskey")
Ingredient.create(name: "dry vermouth")
Ingredient.create(name: "amaretto")
Ingredient.create(name: "tea")
Ingredient.create(name: "champagne")
Ingredient.create(name: "coffee liqueur")
Ingredient.create(name: "bourbon")
Ingredient.create(name: "tequila")
Ingredient.create(name: "vodka")
Ingredient.create(name: "bitters")
Ingredient.create(name: "sugar")
Ingredient.create(name: "kahlua")
Ingredient.create(name: "demerara sugar")
Ingredient.create(name: "dubonnet rouge")
Ingredient.create(name: "lime juice")
Ingredient.create(name: "irish whiskey")
Ingredient.create(name: "apple brandy")
Ingredient.create(name: "carbonated water")
Ingredient.create(name: "cherry brandy")
Ingredient.create(name: "creme de cacao")
Ingredient.create(name: "grenadine")
Ingredient.create(name: "porto")
Ingredient.create(name: "coffee brandy")
Ingredient.create(name: "red wine")
Ingredient.create(name: "rhum")
Ingredient.create(name: "grapefruit juice")
Ingredient.create(name: "ricard")
Ingredient.create(name: "sherry")
Ingredient.create(name: "cognac")
Ingredient.create(name: "sloe gin")
Ingredient.create(name: "apple juice")
Ingredient.create(name: "pineapple juice")
Ingredient.create(name: "lemon juice")
Ingredient.create(name: "sugar syrup")
Ingredient.create(name: "milk")
Ingredient.create(name: "strawberries")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
Ingredient.create(name: "lemon")
