# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "applejack")
Ingredient.create(name: "light rum")
Ingredient.create(name: "gin")
Ingredient.create(name: "dark rhum")
Ingredient.create(name: "sweet vermouth")
Ingredient.create(name: "strawberry schnapps")
Ingredient.create(name: "scotch")
Ingredient.create(name: "apricot brandy")
Ingredient.create(name: "triple sec")
Ingredient.create(name: "southern comfort")
Ingredient.create(name: "orange bitters")
Ingredient.create(name: "brandy")
Ingredient.create(name: "lemon vodka")
Ingredient.create(name: "blended whiskey")
Ingredient.create(name: "dry vermouth")
Ingredient.create(name: "amaretto")
Ingredient.create(name: "tea")
Ingredient.create(name: "champagne")
Ingredient.create(name: "coffee liqueur")
Ingredient.create(name: "bourbon")
Ingredient.create(name: "tequila")
Ingredient.create(name: "vodka")
Ingredient.create(name: "bitters")
Ingredient.create(name: "sugar")
Ingredient.create(name: "kahlua")
Ingredient.create(name: "demerara sugar")
Ingredient.create(name: "dubonnet rouge")
Ingredient.create(name: "lime juice")
Ingredient.create(name: "irish whiskey")
Ingredient.create(name: "apple brandy")
Ingredient.create(name: "carbonated water")
Ingredient.create(name: "cherry brandy")
Ingredient.create(name: "creme de cacao")
Ingredient.create(name: "grenadine")
Ingredient.create(name: "porto")
Ingredient.create(name: "coffee brandy")
Ingredient.create(name: "red wine")
Ingredient.create(name: "rhum")
Ingredient.create(name: "grapefruit juice")
Ingredient.create(name: "ricard")
Ingredient.create(name: "sherry")
Ingredient.create(name: "cognac")
Ingredient.create(name: "sloe gin")
Ingredient.create(name: "apple juice")
Ingredient.create(name: "pineapple juice")
Ingredient.create(name: "lemon juice")
Ingredient.create(name: "sugar syrup")
Ingredient.create(name: "milk")
Ingredient.create(name: "strawberries")
Ingredient.create(name: "chocolate syrup")
Ingredient.create(name: "yoghurt")
Ingredient.create(name: "mango")
Ingredient.create(name: "ginger")
Ingredient.create(name: "lime")
Ingredient.create(name: "cantaloupe")
Ingredient.create(name: "berries")
Ingredient.create(name: "grapes")
Ingredient.create(name: "kiwi")
Ingredient.create(name: "tomato juice")
Ingredient.create(name: "cocoa powder")
Ingredient.create(name: "chocolate")
Ingredient.create(name: "heavy cream")
Ingredient.create(name: "galliano")
Ingredient.create(name: "peach vodka")
Ingredient.create(name: "ouzo")
Ingredient.create(name: "coffee")
Ingredient.create(name: "spiced rhum")
Ingredient.create(name: "water")
Ingredient.create(name: "espresso")
Ingredient.create(name: "angelica root")
Ingredient.create(name: "orange")
Ingredient.create(name: "cranberries")
Ingredient.create(name: "johnnie walker")
Ingredient.create(name: "apple cider")
Ingredient.create(name: "everclear")
Ingredient.create(name: "cranberry juice")
Ingredient.create(name: "egg yolk")
Ingredient.create(name: "egg")
Ingredient.create(name: "grape juice")
Ingredient.create(name: "peach nectar")
Ingredient.create(name: "firewater")
Ingredient.create(name: "lemonade")
Ingredient.create(name: "lager")
Ingredient.create(name: "whiskey")
Ingredient.create(name: "absolute citron")
Ingredient.create(name: "pisco")
Ingredient.create(name: "irish cream")
Ingredient.create(name: "ale")
Ingredient.create(name: "chocolate liqueur")
Ingredient.create(name: "midori melon liqueur")
Ingredient.create(name: "sambuca")
Ingredient.create(name: "cider")
Ingredient.create(name: "sprite")
Ingredient.create(name: "7-up")
Ingredient.create(name: "blackberry brandy")
Ingredient.create(name: "creme de cassis")
Ingredient.create(name: "jack daniels")
Ingredient.create(name: "bailey's irish cream")
Ingredient.create(name: "151 proof rhum")
Ingredient.create(name: "absolut vodka")
Ingredient.create(name: "goldschlager")
Ingredient.create(name: "crown royal")
Ingredient.create(name: "cointreau")
Ingredient.create(name: "vermouth")
Ingredient.create(name: "advocat")
Ingredient.create(name: "absolut kurant")
Ingredient.create(name: "beer")
Ingredient.create(name: "kool-aid")
Ingredient.create(name: "cherry heering")
Ingredient.create(name: "white creme de menthe")
Ingredient.create(name: "malibu rhum")
Ingredient.create(name: "vanilla vodka")
Ingredient.create(name: "jagermeister")
Ingredient.create(name: "kiwi liqueur")
Ingredient.create(name: "grand marnier")
Ingredient.create(name: "cachaca")
Ingredient.create(name: "peachtree schnapps")
Ingredient.create(name: "wild turkey")
Ingredient.create(name: "cranberry vodka")
Ingredient.create(name: "corona")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "yukon jack")
Ingredient.create(name: "chocolate ice-cream")
Ingredient.create(name: "coconut rhum")
Ingredient.create(name: "banana liqueur")
Ingredient.create(name: "black sambuca")
Ingredient.create(name: "hot damn")
Ingredient.create(name: "mint")
Ingredient.create(name: "campari")
Ingredient.create(name: "sour mix")
Ingredient.create(name: "absinthe")
Ingredient.create(name: "guinness stout")
Ingredient.create(name: "vanilla ice-cream")
Ingredient.create(name: "chambord raspberry liqueur")
Ingredient.create(name: "jim beam")
Ingredient.create(name: "godiva liqueur")
Ingredient.create(name: "fruit punch")
Ingredient.create(name: "zima")
Ingredient.create(name: "blue caracao")
Ingredient.create(name: "coca-cola")
Ingredient.create(name: "maui")
Ingredient.create(name: "frangelico")
Ingredient.create(name: "bacardi limon")
Ingredient.create(name: "raspberry vodka")
Ingredient.create(name: "green creme de menthe")
Ingredient.create(name: "lemon peel")
Ingredient.create(name: "prosecco")
Ingredient.create(name: "mezcal")
Ingredient.create(name: "green chartreuse")
Ingredient.create(name: "grape soda")
Ingredient.create(name: "hot chocolate")
Ingredient.create(name: "blended scotch")
Ingredient.create(name: "rye whiskey")
